### ISSUE TITLE
ALB support

### ISSUE THREAD

**Issue by limitusus** [winebarrel/kelbim#7]
I would be glad if kelbim supports ALB.

BTW Can v0.3.0 be released?

**Comment by winebarrel** [comment]
I will plan to make new tool for ALB.
But I have no time...

> BTW Can v0.3.0 be released?

yes. please wait.

**Comment by winebarrel** [comment]
released.

**Comment by limitusus** [comment]
Great. Thank you.

**Comment by winebarrel** [comment]
A similar tool have been created by @wata-gh
see https://github.com/wata-gh/applb

**Comment by wata-gh** [comment]
thanks for introduction!
